name: Mirror and Push Branch

on:
  push:
    branches:
      - main

jobs:
  mirrorAndPush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Git user
        run: |
          git config --global user.name "MikuX-Dev"
          git config --global user.email "abinishanth3464@gmail.com"
    
      - name: Fetch source repository
        run: |
          git remote add source https://github.com/Project-Mikasa/kernel_xiaomi_ysl.git
          git fetch source
          
      - name: Push mikasa branch to target repository
        run: |
          git remote add target https://github.com/MikuX-Dev/Kernel-ysl.git
          git pull target main
          git push target refs/remotes/source/mikasa:refs/heads/target/main
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
