name: Mirror and Push Branch

on:
  push:
    branches:
      - main

jobs:
  mirrorAndPush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone source repository
        run: git clone --mirror https://github.com/Project-Mikasa/kernel_xiaomi_ysl.git kernel_xiaomi_ysl
      
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    
      - name: Push Mikasa branch to target repository
        run: |
          git remote add source https://github.com/Project-Mikasa/kernel_xiaomi_ysl.git
          git fetch source mikasa:mikasa
          git remote add target https://github.com/MikuX-Dev/Kernel-ysl.git
          git push target source/mikasa:refs/heads/main
