name: Mirror and Push Branch

on:
  push:
    branches:
      - main

jobs:
  mirrorAndPush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    
      - name: Push v2.0-Velocy tag to target repository
        run: |
          git remote add source https://github.com/Project-Mikasa/kernel_xiaomi_ysl.git
          git fetch source v2.0-Velocy
          git remote add target https://github.com/MikuX-Dev/Kernel-ysl.git
          git checkout -b main
          git push target v2.0-Velocy:main
          
