name: Push Branch

on:
  push:
    branches:
      - main

jobs:
  pushBranch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone source repository
        run: git clone --branch mikasa https://github.com/Project-Mikasa/kernel_xiaomi_ysl.git
      
      - name: Set up Git user
        run: |
          git config --global user.name "MikuX-Dev"
          git config --global user.email "abinishanth3464@gmail.com"
      
      - name: Push branch to target repository
        run: |
          cd kernel_xiaomi_ysl
          git remote set-url origin https://github.com/MikuX-Dev/Kernel-ysl.git
          git push --mirror https://$PAT_TOKEN@github.com/MikuX-Dev/Kernel-ysl.git
