name: merge kernel

on:
  push:
    branches:
      - C # Modify this if your main branch has a different name

env:
  GH_TOKEN: ${{ secrets.PAT_TOKEN }}
  lp: logan_perf
  lc: logan_common
  mk: mikasa
  cf: python3 resolve_conflicts.py

jobs:
  rebase_kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "MikuX-Dev"
          git config --global user.email "abinishanth3464@gmail.com"

      - name: Clone repo
        run: |
          git clone https://github.com/Noob-214/Logan_Ysl.git -b $lc
          git clone https://github.com/Noob-214/Logan_Ysl.git -b $lp
          git clone https://github.com/Project-Mikasa/kernel_xiaomi_ysl.git -b $mk

      - name: Fetch Latest Source
        run: git fetch origin

      - name: Rebase
        run: |
          git checkout test
          git rebase upstream/perf || true  # Continue even if rebase fails
      
      - name: Check for Conflicts
        run: |
          CONFLICTS=$(git diff --name-only --diff-filter=U)
          if [[ -n "$CONFLICTS" ]]; then
            echo "Conflicts detected. Resolving conflicts..."
            python resolve_conflicts.py
            git add .
            git rebase --continue
          fi

      - name: Push Changes
        run: git push --force-with-lease origin test
